# Generated by Django 6.0.7 on 2026-07-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_category_task_category'),
        ('todo', '0002_task_priority'),
    ]

    operations = [
    ]
